// Vlož do bazos.sk karty: zobrazí fotku N inzerátu ID na ružovom pozadí (na zoom), alebo prehľad náhľadov všetkých fotiek.
// Autá z vlastných webov predajcov (adId 9xxxxxxxx): fotky sa berú z https://www.splatkuj.sk/api/foto/<id>/<n> (server ich má podľa imgs v admine).
window.IMGS=window.IMGS||{};window.SRC=(id,n,t)=>window.IMGS[id]?window.IMGS[id][n-1]:/^9\d{8}$/.test(id)?`https://www.splatkuj.sk/api/foto/${id}/${n}`:`https://www.bazos.sk/img/${n}${t?'t':''}/${id.slice(-3)}/${id}.jpg?t=${Date.now()}`;
window.S2=(id,n)=>new Promise(res=>{document.getElementById('gs')?.remove();let g=document.getElementById('gg');if(!g){g=document.createElement('div');g.id='gg';g.style.cssText='position:fixed;left:0;top:0;width:100vw;height:100vh;background:#ff00ff;z-index:2147483647;';document.body.appendChild(g);}
g.innerHTML='';const im=document.createElement('img');im.style.cssText='position:absolute;left:0;top:0;max-width:none';im.onload=()=>res(im.naturalWidth+'x'+im.naturalHeight);im.onerror=()=>res('err');setTimeout(()=>res('timeout'),8000);g.appendChild(im);im.src=window.SRC(id,n,false);});
window.SHEET=async(cars)=>{document.getElementById('gg')?.remove();let g=document.getElementById('gs');if(!g){g=document.createElement('div');g.id='gs';g.style.cssText='position:fixed;inset:0;background:#fff;z-index:2147483647;overflow:hidden;font:bold 18px sans-serif';document.body.appendChild(g);}
g.innerHTML='';const ps=[];for(const [id,cnt] of cars){const row=document.createElement('div');row.style.cssText='display:flex;flex-wrap:wrap;gap:4px;margin:0 0 8px';row.innerHTML=`<div style="width:90px;color:#c00">${id.slice(-4)}</div>`;
for(let n=1;n<=cnt;n++){const d=document.createElement('div');d.style.cssText='position:relative;width:150px;height:112px;background:#ddd';const im=new Image();im.style.cssText='width:100%;height:100%;object-fit:cover';ps.push(new Promise(r=>{im.onload=im.onerror=r}));im.src=window.SRC(id,n,true);d.append(im);const l=document.createElement('b');l.textContent=n;l.style.cssText='position:absolute;left:3px;top:1px;color:#ff0;text-shadow:0 0 3px #000,0 0 3px #000';d.append(l);row.append(d);}g.append(row);}
await Promise.all(ps);return 'ok';};
'S2 ready'
